Use SDBM
GO

CREATE TABLE COULEUR
(
	ID_COULEUR int IDENTITY(1,1) NOT NULL,
	NOM_COULEUR varchar(25) NOT NULL,
	CONSTRAINT PK_COULEUR PRIMARY KEY CLUSTERED 
	(
		ID_COULEUR ASC
	)
) 
GO

CREATE TABLE CONTINENT
(
	ID_CONTINENT int IDENTITY(1,1) NOT NULL,
	NOM_CONTINENT varchar(25) NOT NULL,
	CONSTRAINT PK_CONTINENT PRIMARY KEY CLUSTERED 
	(
		ID_CONTINENT ASC
	)
)
GO

CREATE TABLE PAYS
(
	ID_PAYS int IDENTITY(1,1) NOT NULL,
	NOM_PAYS varchar(40) NOT NULL,
	ID_CONTINENT int NOT NULL,
	CONSTRAINT PK_PAYS PRIMARY KEY CLUSTERED 
	(
		ID_PAYS ASC
	)
)
GO

CREATE TABLE TYPEBIERE
(
	ID_TYPE int IDENTITY(1,1) NOT NULL,
	NOM_TYPE varchar(25) NOT NULL,
	CONSTRAINT PK_TYPEBIERE PRIMARY KEY CLUSTERED 
	(
		ID_TYPE ASC
	)
)
GO

CREATE TABLE FABRICANT
(
	ID_FABRICANT int IDENTITY(1,1) NOT NULL,
	NOM_FABRICANT varchar(40) NOT NULL,
	CONSTRAINT PK_FABRICANT PRIMARY KEY NONCLUSTERED 
	(
		ID_FABRICANT ASC
	)
) 
GO

CREATE TABLE MARQUE
(
	ID_MARQUE int IDENTITY(1,1) NOT NULL,
	NOM_MARQUE varchar(40) NOT NULL,
	ID_PAYS int NOT NULL,
	ID_FABRICANT int NULL,
	CONSTRAINT PK_MARQUE PRIMARY KEY NONCLUSTERED 
	(
		ID_MARQUE ASC
	)
) 
GO


ALTER TABLE MARQUE  WITH CHECK ADD CONSTRAINT FK_MARQUE_FABRICANT FOREIGN KEY(ID_FABRICANT)
REFERENCES FABRICANT (ID_FABRICANT)
GO

ALTER TABLE MARQUE  WITH CHECK ADD CONSTRAINT FK_MARQUE_PAYS FOREIGN KEY(ID_PAYS)
REFERENCES PAYS (ID_PAYS)
GO


ALTER TABLE PAYS  WITH CHECK ADD  CONSTRAINT FK_PAYS_CONTINENT FOREIGN KEY(ID_CONTINENT)
REFERENCES CONTINENT (ID_CONTINENT)
GO


